import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Abbas',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirts',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Apopular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirts',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Apopular shirt',
    },
    {
      name: 'slim Shirt',
      slug: 'slim-shirts',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 90,
      brand: 'Reybond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Apopular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',

      category: 'Pants',
      image: '/images/p1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'fit Pants',
      slug: 'fit-pants',

      category: 'Pants',
      image: '/images/p2.jpg',
      price: 90,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Apopular pants',
    },
    {
      name: 'classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 95,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Apopular pants',
    },
  ],
};

export default data;
